name: cp2k
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: v1.1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 3a9f1e6394807a8483cd5a4d3ed617779221c64a # develop-26-02-10
modules: True
version: 2
